#!/bin/bash
if [ "$(uname)" == "Darwin" ]; then
    # Do something under Mac OS X platform

    echo "

    #### IMPORTANT ####

    You will need to run every command from ~/.hc-vim/mac-dependencies
    before you continue!!

    "

    while true; do
        read -p "Do you installed the dependencies?[Y/n]: " yn
        case $yn in
            [Yy]* ) break;;
            [Nn]* ) echo "Run it then come back later!"; exit;;
            * ) echo "Please answer Y(Yes) or n(no).";;
        esac
    done

    declare -a FILES_TO_BACKUP=(.vim .vimrc .eslintrc)

elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    # Do something under GNU/Linux platform

    echo "

    #### IMPORTANT ####

    Please accept the execution of ubuntu-dependencies file.
    If you want todo it later, you can run the following command yourself:
    --> bash ~/.hc-vim/ubuntu-dependencies

    ! Mandatory for vim to have correct fonts, YouCompleteMe to work
    and to have some linters working!

    ! Be sure your user is a sudoer when you run ubuntu-dependencies.!

    "

    while true; do
        read -p "Do you want to proceed to installing dependencies?[Y/n]: " yn
        case $yn in
            [Yy]* ) bash ~/.hc-vim/ubuntu-dependencies; break;;
            [Nn]* ) echo "Ok. Don't forget to run bash ~/.hc-vim/ubuntu-dependencies later!"; exit;;
            * ) echo "Please answer Y(Yes) or n(no).";;
        esac
    done

    declare -a FILES_TO_BACKUP=(.vim .vimrc .eslintrc .gtkrc-2.0)

elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
    # Do something under 32 bits Windows NT platform

    echo "Sorry, can't do anything for you!"
    exit 1
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
    # Do something under 64 bits Windows NT platform

    echo "Sorry, can't do anything for you!"
    exit 1
fi
