#!/bin/bash

# Install required dependencies
sudo apt-get -y install vim vim-gtk
sudo apt-get -y install build-essential cmake curl
sudo apt-get -y install python-dev python3-dev

# Install nodejs + npm
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs

#### Linters ####

# Javascript
sudo npm install -g babel-eslint

# Python
sudo apt-get install pylint

#### Code formatters ####

# JS/HTML/CSS/JSON
npm install -g js-beautify

# Typescript
npm install -g typescript-formatter

# C/C++/Objective C
sudo apt-get install clang-format
