#!/bin/bash

while true; do
    read -p "Are you a sudoer?[Y/n]: " yn
    case $yn in
        [Yy]* ) echo "Ok. Let's proceed to password."; break;;
        [Nn]* ) echo "It's not possible to run this script. Try running commands from this script on your own."; exit;;
        * ) echo "Please answer Y(Yes) or n(no).";;
    esac
done

# Install required dependencies
sudo apt-get -y install vim vim-gtk

# Dependencies for YOuCompleteMe
sudo apt-get -y install build-essential cmake curl
sudo apt-get -y install python-dev python3-dev

#### Auto Complete ####

# Sometimes it my not execute. Execute it yourself, like you should normaly do,
# For more information, check the YouCompleteMe Documentation
echo "
-- Compiling YouCompleteMe
"
python3 ~/.vim/bundle/YouCompleteMe/install.py --all
# The following error will pop up: "ERROR: msbuild or xbuild is required to build Omnisharp.".
# Don't worry, is from C# and all other features but C# auto-complete will work fine.

#### Install the fonts ####
echo "
-- Creating ~/.fonts folder if not exits
"
if [ ! -d ~/.fonts ]; then
    mkdir ~/.fonts
fi
echo "
-- Coping all the fonts
"
sudo cp -f ~/.hc-vim/fonts/* ~/.fonts/
echo "
-- Making the OS aware of the new fonts
"
sudo fc-cache -f

# Install nodejs + npm
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs

#### Linters ####

# Javascript
sudo npm install -g babel-eslint

# Python
sudo apt-get install pylint

#### Code formatters ####

# JS/HTML/CSS/JSON
sudo npm install -g js-beautify

# Typescript
sudo npm install -g typescript typescript-formatter

# C/C++/Objective C
sudo apt-get install clang-format
