#!/bin/bash

# Bash script for setting up configurations and plugins for Vim.

echo "
 ██░ ██  ▄████▄      ██▒   █▓ ██▓ ███▄ ▄███▓
 ██░ ██▒▒██▀ ▀█     ▓██░   █▒▓██▒▓██▒▀█▀ ██▒
▒██▀▀██░▒▓█    ▄     ▓██  █▒░▒██▒▓██    ▓██░
░▓█ ░██ ▒▓▓▄ ▄██▒     ▒██ █░░░██░▒██    ▒██ 
░▓█▒░██▓▒ ▓███▀ ░      ▒▀█░  ░██░▒██▒   ░██▒
 ▒ ░░▒░▒░ ░▒ ▒  ░      ░ ▐░  ░▓  ░ ▒░   ░  ░
 ▒ ░▒░ ░  ░  ▒         ░ ░░   ▒ ░░  ░      ░
 ░  ░░ ░░                ░░   ▒ ░░      ░   
 ░  ░  ░░ ░               ░   ░         ░   
        ░                ░                  
"
HOME_PREFIX=~/
declare -a FILES_TO_BACKUP=(.vim .vimrc .eslintrc .gtkrc-2.0)

echo "
-- Cloning the hc-vim repository to ~/.hc-vim
"
git clone https://github.com/horea-chivu/hc-vim ~/.hc-vim

# Backup old files that could possibly be replaced
echo "
-- Creating ~/.vim_backup directory(if not allready exist)
"
if [ ! -d ~/.vim_backup ]; then
    mkdir ~/.vim_backup
fi
echo "
-- Moving your existing(if exist) files to ~/.vim_backup
"
for file in ${FILES_TO_BACKUP[@]}; do
    if [ -e $HOME_PREFIX$file ]; then
        mv $HOME_PREFIX$file ~/.vim_backup
    fi
done

mkdir ~/.vim
echo "
-- Creating symbolic links for the configuration files
"
ln -s ~/.hc-vim/colors ~/.vim/
ln -s ~/.hc-vim/.vimrc ~/
ln -s  ~/.hc-vim/plugins.vim ~/.vim/

echo "
-- Creating symbolic links for .gtkrc-2.0 and .eslintrc
"
# For the borders problem in gVim
ln -s ~/.hc-vim/needed_files/.gtkrc-2.0 ~/

# Conf for eslint
ln -s ~/.hc-vim/needed_files/.eslintrc ~/

echo "
-- Cloning Vundle repository
"
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

echo "
-- Install the plugins
"
vim +PluginInstall +qall

# Install the fonts
echo "
-- Creating ~/.fonts folder if not exits
"
if [ ! -d ~/.fonts ]; then
    mkdir ~/.fonts
fi
echo "
-- Coping all the fonts
"
sudo cp -f ~/.hc-vim/fonts/* ~/.fonts/
echo "
-- Making the OS aware of the new fonts
"
sudo fc-cache -f

echo "

-- For Ubuntu based OS(Ubuntu, Mint, etc).

Please execute ubuntu-dependencies file yourself.
command: bash ~/.hc-vim/ubuntu-dependencies

Mandatory for vim to work correctly with plugins.

"
