#!/bin/bash

HOME_PREFIX=~/
declare -a SYM_TO_REMOVE=(.vimrc .gtkrc-2.0 .eslintrc)
declare -a CONFIGS_TO_REMOVE=(.vim.user.before .vim.user.after .vim.user.settings)
declare -a DIRS_TO_REMOVE=(.vim .hc-vim)

while true; do
    read -p "Do you want to remove the .vim.user.* files?[Y/n]: " yn
    case $yn in

        [Yy]* )
                echo "
                -- Removing .vim.user.* files related to this config
                "
                for file in ${CONFIGS_TO_REMOVE[@]}; do
                    if [ -e $HOME_PREFIX$file ]; then
                        rm -f $HOME_PREFIX$file
                    fi
                done
                ;;
        [Nn]* )
                echo "
                -- The .vim.user.* will not be removed
                "
                ;;
        * )
                echo "
                Please answer Y(Yes) or n(no).
                "
                ;;
    esac
done


# Remove symbolic files
echo "
-- Removing symbolic links
"
for file in ${SYM_TO_REMOVE[@]}; do
    if [ -e $HOME_PREFIX$file ]; then
        rm -f $HOME_PREFIX$file
    fi
done

echo "
-- Removing directories
"
for file in ${DIRS_TO_REMOVE[@]}; do
    if [ -e $HOME_PREFIX$file ]; then
        rm -fR $HOME_PREFIX$file
    fi
done
