#!/bin/bash

HOME_PREFIX=~/
declare -a SYM_TO_REMOVE=(.vimrc .eslintrc)
declare -a DIRS_TO_REMOVE=(.vim .hc-vim)

while true; do
    read -p "Do you want to remove the .vim.user directory(contain all your custom configurations, plugins, plugins settings)?[Y/n]: " yn
    case $yn in

        [Yy]* )
                echo "
                -- Removing ~/.vim.user directory
                "
                if [ -d ~/.vim.user ]; then
                    rm -fR ~/.vim.user
                fi
                break
                ;;
        [Nn]* )
                echo "
                -- The .vim.user directory will not be removed(you custom configuration files will be preserved)
                "
                break
                ;;
        * )
                echo "
                Please answer Y(Yes) or n(no).
                "
                ;;
    esac
done


# Remove symbolic files
echo "
-- Removing symbolic links
"
for file in ${SYM_TO_REMOVE[@]}; do
    if [ -e $HOME_PREFIX$file ]; then
        rm -f $HOME_PREFIX$file
    fi
done

# If is Linux, delete the symbolic link with gtk configuration
if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    rm -f ~/.gtkrc-2.0
fi

echo "
-- Removing directories
"
for file in ${DIRS_TO_REMOVE[@]}; do
    if [ -e $HOME_PREFIX$file ]; then
        rm -fR $HOME_PREFIX$file
    fi
done
